/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Main overlay structure with optimized architecture */
export declare class Overlay {
  constructor()
  /** Start the overlay system with optimized event loop */
  start(): void
  /** Update frame with optimized buffer handling */
  updateFrame(buffer: Buffer): void
  /** Get frame size with improved calculation */
  getFrameSize(): Array<number>
  /** Window visibility controls */
  show(): void
  hide(): void
  isVisible(): boolean
  /** Window positioning */
  setPosition(x: number, y: number): void
  getPosition(): WindowPosition
  /** Window sizing */
  setSize(width: number, height: number): void
  getSize(): WindowSize
  /** Window properties */
  setTitle(title: string): void
  setWindowLevel(level: WindowLevel): void
  requestRedraw(): void
  /** Frame operations */
  clearFrame(color: Color): void
  drawRectangle(x: number, y: number, width: number, height: number, color: Color): void
  /** Get the current frame buffer for advanced manipulations */
  getFrameBuffer(): Buffer
  /** Manually trigger a render of the current frame */
  render(): void
  /** Resize the frame buffer and window */
  resize(width: number, height: number): void
}

export declare function blendColors(foreground: Color, background: Color): Color

export declare function calculateBufferSizeNapi(width: number, height: number): number

export interface Color {
  r: number
  g: number
  b: number
  a: number
}

export declare function colorBlack(): Color

export declare function colorBlue(): Color

export declare function colorCyan(): Color

export declare function colorDarkGray(): Color

export declare function colorGray(): Color

export declare function colorGreen(): Color

export declare function colorLightGray(): Color

export declare function colorMagenta(): Color

export declare function colorOrange(): Color

export declare function colorPink(): Color

export declare function colorRed(): Color

export declare function colorToHex(color: Color): string

export declare function colorToRgba(color: Color): Array<number>

export declare function colorToRgbHex(color: Color): string

export declare function colorTransparent(): Color

export declare function colorWhite(): Color

export declare function colorYellow(): Color

export declare function createColor(r: number, g: number, b: number, a: number): Color

export declare function createPosition(x: number, y: number): WindowPosition

export declare function createRgbaBuffer(width: number, height: number): Buffer

export declare function createSize(width: number, height: number): WindowSize

export interface DecodedImage {
  data: Buffer
  width: number
  height: number
}

export declare function drawCircle(
  buffer: Buffer,
  cx: number,
  cy: number,
  radius: number,
  bufferWidth: number,
  bufferHeight: number,
  color: Color,
): Buffer

export declare function drawLine(buffer: Buffer, params: LineParams): Buffer

export declare function drawPixel(buffer: Buffer, x: number, y: number, width: number, color: Color): Buffer

export declare function fillBufferColor(buffer: Buffer, color: Color): Buffer

export declare function lerpColors(color1: Color, color2: Color, t: number): Color

export interface LineParams {
  x1: number
  y1: number
  x2: number
  y2: number
  bufferWidth: number
  bufferHeight: number
  color: Color
}

/** Load and decode image from file path */
export declare function loadImage(path: string): DecodedImage

export declare const enum WindowLevel {
  Normal = 0,
  AlwaysOnTop = 1,
  AlwaysOnBottom = 2,
}

export interface WindowPosition {
  x: number
  y: number
}

export interface WindowSize {
  width: number
  height: number
}
