/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Overlay {
  constructor()
  start(): void
  updateFrame(buffer: Buffer): void
  getFrameSize(): Array<number>
}

export declare function plus100(input: number): number
